# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tobias Helmrich | Web and Mobile Developer
email: me@tobiashelmri.ch
description: The personal website of Tobias Helmrich, a web and mobile developer from Germany.
url: "http://tobiashelmri.ch" # the base hostname & protocol for your site
twitter_username: tobias_helmrich
github_username:  helmrich

# Build settings
markdown: kramdown
permalink: /:title

# Default settings
defaults:
  -
    scope:
      path: /blog
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: Tobias Helmrich
      category: Web Development, Mobile Development
